#Object Definitions
===================================================================================================================
CreateTest               xpath     //div[text()='Create Test']
AssessmentCreation       xpath     //div[text()='Assessment Creation']
AssessmentType           xpath     //div[contains(text(),'${Text}')]
Onlinebtn                xpath     //div[contains(text(),'Online')]
Options                  xpath     //span[contains(text(),'${Text}')]
QuestionPaper            xpath     //span[text()='Question Paper']
Download                 xpath     //a[text()='Download Assessment']
Close                    xpath     //button[text()='Close']    
Nextbtn                  xpath     //button[text()='Next']
Nextbutton               xpath     //div[@id='Add_Questions']//button[text()='Next']
PenAndPaper              xpath     //div[contains(text(),'Pen and Paper')]
PickQuestion             xpath     //div[contains(text(),'Pick Question')]
UploadPdf                xpath     //div[contains(text(),'Upload')]
SubjectivePage           xpath     //div[contains(text(),'Subjective')]
txtfield                 xpath     //label[contains(text(),'${Text}')]
Heading                  xpath     //div[text()='ASSESSMENTS']
textfield                xpath     //input[@id='${text}']
AddInstructions          xpath     //textarea[@id='assesmentInst']
fields_Dropdown          xpath    //mat-label[text()='${text}']
dropdown_SelectValue     xpath    //span[text()=' ${text} ']
Import                   xpath    //a[text()=' Import From Question Bank ']
AddNewQuestion           xpath    //label[text()='Add New Question ']
Cancelbtn                xpath    //div[@id='Add_Questions']//div[contains(@class,'bottom-btn')]//a
Canbtn                   xpath    //a[text()='Cancel']
Previous                 xpath    //button[text()='Previous']
Chapter                  xpath    //mat-label[text()='Chapter']
QuesText                 xpath    //textarea[contains(@id,'newQText')]
AnsText                  xpath    //textarea[contains(@id,'newAnswerText')]
Savebtn                  xpath    //button[text()='Save']
Msg                      xpath    //simple-snack-bar
lvl                      xpath    //mat-label[text()='${text}']
lvloption                xpath    //span[contains(text(),'${text}')]
===================================================================================================================