#Object Definitions
===================================================================================================================
Teach                  xpath     //div[contains(text(),'Teach')]
Class                  xpath     //div[contains(@class,'section-title')]
Subject                xpath     //div[contains(@class,'row')]
SubjectName            xpath     //div//p[contains(text(),'${Text}')]
Chapters               xpath     //p[contains(text(),'Chapters')]
expand                 xpath     //div[@id='01']//img[contains(@class,'expand-collapse')]
collapse               xpath     //div[@id='01']//img[contains(@src,'assets/images/learnflix/drop-up.svg')]
Heading                xpath     //div[contains(@class,'learnflix-bookshelf')]
filterOptions          xpath     //div[@id='01']//div[contains(text(),'${Text}')]
ChapterAnalyticsbtn    xpath     //span[contains(text(),'Chapter Analytics')]
ebooks                 xpath     //p[contains(text(),'Recommended eBook')]
Library                xpath     //p[contains(text(),'Library')]
Core                   xpath     //p[contains(text(),'Core')]
Analytics              xpath     //span[contains(text(),'Analytics')]
FilterOptions          xpath     //p[contains(text(),'${Text}')]
filterOptionsCollapsed xpath     //span[contains(text(),'${Text}')]
Concepts               xpath     //div[contains(text(),'${Text}')]
SubConceptsVideo       xpath     (//p[text()='VIDEO'])[1]
PlayBtn                xpath     //img[contains(@alt,'play')]
FullScreen             xpath     //img[contains(@alt,'icon')]
ExitFullScreen         xpath     //img[contains(@class,'normal')]
Video                  xpath     //video[contains(@id,'video_player')]
focus                  xpath     //div[@class='video-desc']
Forward                xpath     //img[@alt='move']
Rewind                 xpath     //img[@alt='back']
Next                   xpath     //button[text()='Next']
Question               xpath     //p[contains(text(),'QUESTION')]
SubmitbtnDisabled      xpath     //button[contains(@class,'disabled-button')]
SelectOpt              xpath     (//div[contains(@class,'option-text')])[1]
SubmitbtnEnabled       xpath     //button[text()='Submit']
Explanation            xpath     //span[text()='EXPLANATION']
Done                   xpath     //button[text()='Done']
Revise                 xpath     //div[contains(@class,'revision-content')]
BackIcon               xpath     //img[contains(@class,'mouse-pointer')]
ObjectivePractice      xpath     //p[contains(text(),'Objective')]
back                   xpath     (//img[contains(@src,'learnflix/close')])[2]
ConceptPractice        xpath     (//p[text()='CONCEPT PRACTICE'])[1]
Startbtn               xpath      //span[text()='Start']
Message                xpath      //p[contains(text(),'Exit')]
Continue               xpath      //span[text()='Continue']
Exitbtn                xpath       //button[text()='Exit Quiz']
ConceptPage            xpath      //p[contains(text(),'Comparing and')]
Conceptback            xpath      //img[contains(@class,'concept-back')]
Analyticsbtn           xpath      //span[text()='Analytics']
Analytics              xpath      //p[text()='Analytics']
ChapterAnalytics       xpath      (//button[contains(@class,'button-default')])[1]
WatchVideo             xpath       //button[text()='Watch Video']
===================================================================================================================